// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://werfsbezbsprestfpsxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcmZzYmV6YnNwcmVzdGZwc3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzQ2OTIsImV4cCI6MjA2NzUxMDY5Mn0.MElbqL3IrwYClRjgHXESBeIgNq8iWbBptm5NR46gO6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});